test_that("CIBERSORT setters update both configurations without leaking state", {
  local_config()
  script <- withr::local_tempfile(fileext = ".R")
  signature <- withr::local_tempfile(fileext = ".txt")
  writeLines("# Configuration test only; never executed as CIBERSORT", script)
  writeLines("gene\tA\nG1\t1", signature)
  set_cibersort_binary(script)
  set_cibersort_mat(signature)
  upstream <- get("config_env", asNamespace("immunedeconv"))
  expect_identical(config_env$cibersort_binary, script)
  expect_identical(config_env$cibersort_mat, signature)
  expect_identical(upstream$cibersort_binary, script)
  expect_identical(upstream$cibersort_mat, signature)
})
