# The purpose of this action is to calculate the code coverage and add the results on codecov.io
# codecov.io provides a badge showing the current coverage and generates coverage reports for each pull requests.
#
# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: test-coverage

jobs:
  test-coverage:
    runs-on: ubuntu-22.04
    env:
      GITHUB_PAT: ${{ secrets.TOKEN }}
      CIBERSORTX_EMAIL: ${{ secrets.CIBERSORTX_EMAIL }}
      CIBERSORTX_TOKEN: ${{ secrets.CIBERSORTX_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      
      - name: system deps
        run: sudo apt-get update && sudo apt-get install libcurl4-openssl-dev
      
      - name: install pak
        run: sudo Rscript -e "install.packages(c('pak', 'pkgdepends'))"
        
      - name: install harmony
        run: sudo Rscript -e "pak::pkg_install('PelzKo/harmony')"

      - name: Update system dependencies
        # due to recent versions of GLIBC missing
        run: |
          sudo apt-get update && sudo apt-get install libstdc++6
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::covr
          needs: coverage

      - name: Test coverage
        run: covr::codecov(quiet = FALSE)
        shell: Rscript {0}
